### ISSUE TITLE
no <optional> in xcode 9

### ISSUE THREAD

**Issue by matkatmusic** [CrushedPixel/Polyline2DExample#1]
Howdy.  Xcode 9.4.1 doesn't have std::optional.   it has std::experimental::optional.  the LineSegment.h file uses std::optional.   You might consider adding something that checks if the OS has std::optional or std::experimental::optional.  just a minor change that'll probably be super ugly to fix with macros haha

**Comment by CrushedPixel** [comment]
I've used such a macro in my own projects before, but the latest Xcode on macOS 10.14 does indeed have `std::optional`, so I don't want to support "outdated" versions of the stdlib.

**Comment by matkatmusic** [comment]
What about all of the people that still need to build 32-bit plugins, which
can't be built in Xcode 10+, and can only be built with xcode 9.4.1?

**Comment by CrushedPixel** [comment]
If you need compatibility, you can use this macro before including the library:

```c++
#if __has_include(<optional>)
	#include <optional>
#elif __has_include(<experimental/optional>)
	#include <experimental/optional>
	#define std::optional std::experimental::optional
#endif
```

**Comment by matkatmusic** [comment]
would it be possible to get that change added to the lib in LineSegment.h?
that's where `std::optional` is used.
if I try to do what you suggested, i just get a bunch of errors about `no
type named 'optional' in the global namespace' in `math.h`

I don't want to have to fork your library to make it work with 32 bit
plugins (still a huge market btw!) but it looks like that might need to
happen.
